version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network

  http-backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.http
    environment:
      DATABASE_URL: "postgresql://postgres:mysecretpassword@db:5432/postgres"
    depends_on:
      - db
    ports:
      - "8000:8000"
    networks:
      - app-network

  ws-backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.ws
    environment:
      DATABASE_URL: "postgresql://postgres:mysecretpassword@db:5432/postgres"
    depends_on:
      - http-backend
    ports:
      - "8080:8080"
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    environment:
      DATABASE_URL: "postgresql://postgres:mysecretpassword@db:5432/postgres"
    depends_on:
      - ws-backend
    ports:
      - "3000:3000"
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
    driver: bridge
