FROM node:20-slim AS base

RUN npm install -g pnpm turbo

WORKDIR /app


COPY pnpm-workspace.yaml turbo.json package.json pnpm-lock.yaml ./

COPY ./packages ./packages
COPY ./apps/excelidraw-frontend ./apps/excelidraw-frontend


RUN pnpm install --frozen-lockfile

EXPOSE 3000


CMD ["pnpm", "run", "start:next"]