import type { Metadata } from "next";

import "./globals.css";
import localFont from "next/font/local";

const norse = localFont({
  src: './Norse.otf',
  display: 'swap',
})

export const metadata: Metadata = {
  title: "ValhallaBrush",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>

      </head>
      <body
        className={`antialiased ${norse.className}`} suppressHydrationWarning={true}
      >
        {children}
      </body>
    </html>
  );
}
