import type { Metadata } from "next";

import "./globals.css";


export const metadata: Metadata = {
  title: "ValhallaBrush",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
       <link rel="preconnect" href="https://fonts.googleapis.com"/>
<link rel="preconnect" href="https://fonts.gstatic.com" />
<link href="https://fonts.googleapis.com/css2?family=Odibee+Sans&family=Sour+Gummy:ital,wght@0,100..900;1,100..900&family=Syne+Mono&display=swap" rel="stylesheet"/>
      </head>
      <body
        className={`antialiased` } suppressHydrationWarning={true}
      >
        {children}
      </body>
    </html>
  );
}
