# .github/workflows/deploy-to-staging.yml
name: Deploy to staging

on:
  push:
    branches:
      - production

jobs:
  redeploy_everything:
    name: Deploying everything to staging cluster
    runs-on: ubuntu-latest

    steps:
      - name: SSH into server and deploy
        run: |
          # write the private key to a file and secure it
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ssh_key
          chmod 600 ssh_key

          # SSH and run your deployment commands
          ssh -o StrictHostKeyChecking=no -i ssh_key ubuntu@13.48.138.13 << 'EOF'
            cd Valhalla-brush/ && git pull origin production
            pnpm install
            pnpm run build
            pm2 restart http-backend
            pm2 restart ws-backend
            pm2 restart excelidraw-frontend
          EOF
